### PR TITLE
gx: update base32

### PR DESCRIPTION
**Pull request by Stebalien**
This PR with gx updates has been created using gx-workspace: https://github.com/ipfs/gx-workspace

### CODE REVIEW

**Comment by kevina** [comment]
That a lot of dependencies to update, unless there is an urgent need can we hold off a bit, there are some additional changes I want to propose.

**Comment by Stebalien** [comment]
@kyledrake is blocked on this for some security origins stuff so I'd like to do this sooner rather than later (i.e., in the next few days at the latest, preferably today).

**Comment by kevina** [comment]
I'm okay with the p.r. going in.  However I would like to get a p.r. in for #18 before we update all the deps on go-multibase.

**Comment by Stebalien** [comment]
I see. I think it's best to hold off on this then. Are you working on that or would you like me to take a crack at it?

**Comment by kevina** [comment]
I can do it today, in the next couple of hours.  I have already thought about what needs to be done.

**Comment by Stebalien** [comment]
@kevina thanks :heart:!

**Comment by Stebalien** [comment]
Waiting on https://github.com/multiformats/go-multibase/issues/18

**Pull request closed without merging**
